# Generated by Django 5.1.15 on 2026-05-04 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20, unique=True)),
                ("released_at", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Патч",
                "verbose_name_plural": "Патчи",
                "ordering": ["-released_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("tank", "Танк"),
                            ("fighter", "Боец"),
                            ("assassin", "Убийца"),
                            ("mage", "Маг"),
                            ("marksman", "Стрелок"),
                            ("support", "Саппорт"),
                        ],
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name_ru", models.CharField(max_length=50)),
                ("icon", models.CharField(default="", max_length=50)),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
            },
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_ru", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("specialty", models.CharField(blank=True, max_length=100)),
                ("release_patch", models.CharField(blank=True, max_length=20)),
                ("is_free", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="heroes/"),
                ),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="heroes/icons/"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="heroes",
                        to="meta.role",
                    ),
                ),
                (
                    "secondary_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="heroes_secondary",
                        to="meta.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Герой",
                "verbose_name_plural": "Герои",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TierEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[("S", "S"), ("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=1,
                    ),
                ),
                ("votes_up", models.PositiveIntegerField(default=0)),
                ("votes_down", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_entries",
                        to="meta.hero",
                    ),
                ),
                (
                    "patch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_entries",
                        to="meta.patch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись тирлиста",
                "verbose_name_plural": "Записи тирлиста",
                "ordering": ["tier", "-votes_up"],
                "unique_together": {("hero", "patch")},
            },
        ),
        migrations.CreateModel(
            name="HeroVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_upvote", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tier_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="meta.tierentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Голос",
                "verbose_name_plural": "Голоса",
                "unique_together": {("user", "tier_entry")},
            },
        ),
    ]
