# Generated by Django 5.1.15 on 2026-05-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0004_hero_extra_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="game_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("early", "Ранняя игра"),
                    ("mid", "Средняя игра"),
                    ("late", "Поздняя игра"),
                ],
                default="",
                max_length=10,
                verbose_name="Силён на стадии",
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="has_cc",
            field=models.BooleanField(default=False, verbose_name="Есть контроль"),
        ),
        migrations.AlterField(
            model_name="hero",
            name="has_sustain",
            field=models.BooleanField(
                default=False, verbose_name="Есть восстановление"
            ),
        ),
    ]
