# Generated by Django 5.1.15 on 2026-05-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0005_alter_hero_game_phase_alter_hero_has_cc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название (EN)"
                    ),
                ),
                ("name_ru", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("attack", "Атака"),
                            ("defense", "Защита"),
                            ("magic", "Магия"),
                            ("movement", "Передвижение"),
                            ("jungle", "Джунгли"),
                            ("roaming", "Поддержка"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="items/", verbose_name="Иконка"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Цена (золото)"
                    ),
                ),
                (
                    "patch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="meta.patch",
                        verbose_name="Добавлен в патче",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
                "ordering": ["category", "name_ru"],
            },
        ),
    ]
