# Generated by Django 5.1.15 on 2026-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0006_add_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="tierentry",
            name="ban_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="Бан-рейт (%)"),
        ),
        migrations.AddField(
            model_name="tierentry",
            name="pick_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="Пик-рейт (%)"),
        ),
        migrations.AddField(
            model_name="tierentry",
            name="win_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="Винрейт (%)"),
        ),
    ]
