# Generated by Django 5.1.15 on 2026-05-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0007_tierentry_stats_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
    ]
