# Generated by Django 5.1.15 on 2026-05-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_serviceorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_pro",
            field=models.BooleanField(
                default=False,
                help_text="Пометить услугу как доступную по подписке PRO.",
                verbose_name="Только PRO",
            ),
        ),
    ]
