# Generated by Django 5.1.15 on 2026-05-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_service_is_pro"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        help_text="Список преимуществ, по одному на строку",
                        verbose_name="Что входит",
                    ),
                ),
                ("price", models.CharField(max_length=80, verbose_name="Цена")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Центральный блок со ярким дизайном",
                        verbose_name="Выделенный план",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=100, verbose_name="Порядок"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "План подписки",
                "verbose_name_plural": "Планы подписки",
                "ordering": ["sort_order", "title"],
            },
        ),
    ]
