# Generated by Django 5.1.15 on 2026-05-04 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlossaryTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("definition", models.TextField()),
                ("example", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Термин словаря",
                "verbose_name_plural": "Словарь",
                "ordering": ["term"],
            },
        ),
        migrations.CreateModel(
            name="GuideSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="guides/covers/"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guide_series",
                        to="meta.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Серия гайдов",
                "verbose_name_plural": "Серии гайдов",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("excerpt", models.TextField(blank=True, max_length=400)),
                ("content", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Новичок"),
                            ("intermediate", "Средний"),
                            ("advanced", "Продвинутый"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="guides/"),
                ),
                ("published", models.BooleanField(default=False)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guides",
                        to="guide.guideseries",
                    ),
                ),
            ],
            options={
                "verbose_name": "Гайд",
                "verbose_name_plural": "Гайды",
                "ordering": ["order", "title"],
            },
        ),
    ]
