# Generated by Django 5.1.15 on 2026-05-05 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0001_initial"),
        ("meta", "0005_alter_hero_game_phase_alter_hero_has_cc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="builds",
                        to="meta.hero",
                        verbose_name="Герой",
                    ),
                ),
                (
                    "patch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="builds",
                        to="meta.patch",
                        verbose_name="Патч",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сборка",
                "verbose_name_plural": "Сборки",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
