# Generated by Django 5.1.15 on 2026-05-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0002_build"),
        ("meta", "0006_add_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="items",
            field=models.ManyToManyField(
                blank=True,
                related_name="builds",
                to="meta.item",
                verbose_name="Предметы",
            ),
        ),
        migrations.AddField(
            model_name="build",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="builds",
                to="meta.role",
                verbose_name="Роль",
            ),
        ),
        migrations.AddField(
            model_name="build",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=220, unique=True, verbose_name="Slug"
            ),
        ),
    ]
