# Generated by Django 5.1.15 on 2026-05-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0003_build_slug_items_role"),
        ("meta", "0008_hero_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="hero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guides",
                to="meta.hero",
                verbose_name="Герой",
            ),
        ),
    ]
