# Generated by Django 5.1.15 on 2026-05-05 12:44

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_siteconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("features", "Что внутри"),
                            ("guides", "Последние гайды"),
                            ("builds", "Лучшие сборки"),
                            ("how_it_works", "Как это работает"),
                            ("cta", "Призыв к действию"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Блок",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Блок главной страницы",
                "verbose_name_plural": "Блоки главной страницы",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.core.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
