# Generated by Django 5.1.15 on 2026-05-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_homesection_alter_user_managers_alter_siteconfig_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homesection",
            name="badge",
            field=models.CharField(
                blank=True,
                help_text="Маленький тег над заголовком, необязательно",
                max_length=80,
                verbose_name="Бейдж",
            ),
        ),
        migrations.AddField(
            model_name="homesection",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="Необязательно",
                max_length=400,
                verbose_name="Подзаголовок",
            ),
        ),
        migrations.AddField(
            model_name="homesection",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Оставьте пустым для использования заголовка по умолчанию",
                max_length=200,
                verbose_name="Заголовок",
            ),
        ),
    ]
