# Generated by Django 5.1.15 on 2026-05-05 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_siteuser_avatar"),
        ("services", "0004_subscriptionplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteuser",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscribers",
                to="services.subscriptionplan",
                verbose_name="Подписка PRO",
            ),
        ),
    ]
