# Generated by Django 5.1.15 on 2026-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_siteuser_subscription_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteuser",
            name="subscription_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата начала подписки"
            ),
        ),
    ]
