# Generated by Django 5.1.15 on 2026-05-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0004_siteuser_subscription_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteuser",
            name="subscription_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания подписки"
            ),
        ),
    ]
